### ISSUE TITLE
TypeError: Cannot read property '_statStorage' of undefined

### ISSUE THREAD

**Issue by ccnyou** [SteamerTeam/steamer-react#38]
新建项目后，执行`npm start`报错：

```bash
ERROR in ./page/index/container/index.less (../node_modules/cache-loader/dist/cjs.js??ref--11-1!../node_modules/css-loader??ref--11-2!../node_modules/postcss-loader/src!../node_modules/less-loader/dist/cjs.js??ref--11-4!./page/index/container/index.less)
Module build failed (from ../node_modules/cache-loader/dist/cjs.js):
TypeError: Cannot read property '_statStorage' of undefined
    at stat (/Users/ervin/Documents/Project/git/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:231:8)
    at toDepDetails (/Users/ervin/Documents/Project/git/app/node_modules/cache-loader/dist/index.js:66:5)
    at arrayIterator (/Users/ervin/Documents/Project/git/app/node_modules/neo-async/async.js:3780:9)
    at timesSync (/Users/ervin/Documents/Project/git/app/node_modules/neo-async/async.js:2292:7)
    at Object.mapLimit (/Users/ervin/Documents/Project/git/app/node_modules/neo-async/async.js:3775:5)
    at Array.<anonymous> (/Users/ervin/Documents/Project/git/app/node_modules/cache-loader/dist/index.js:89:18)
    at arrayEachFunc (/Users/ervin/Documents/Project/git/app/node_modules/neo-async/async.js:2512:19)
    at Object.parallel (/Users/ervin/Documents/Project/git/app/node_modules/neo-async/async.js:6867:9)
    at Object.loader (/Users/ervin/Documents/Project/git/app/node_modules/cache-loader/dist/index.js:88:9)
 @ ./page/index/container/index.less 2:14-269 21:1-42:3 22:19-274
 @ ./page/index/container/index.js
 @ ./page/index/root/Root.dev.js
 @ ./page/index/root/Root.hot.js
 @ ./page/index/main.js
 @ multi react-hot-loader/patch webpack-hot-middleware/client?reload=true&dynamicPublicPath=true&path=__webpack_hmr ./page/index/main.js
Child html-res-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  28.4 KiB       0
    Entrypoint undefined = index.html
    [../node_modules/html-res-webpack-plugin/libs/loader.js!./page/index/main.html] 1.08 KiB {0} [built]
ℹ ｢wdm｣: Failed to compile.
```

**Comment by lcxfs1991** [comment]
能报一下 node_modules 里面的 webpack版本吗？
